<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Magepow\CheckoutCustom\Model\Data\CustomFields $customFields */
$customFields = $block->getOrderCustomFields();
?>
<?php if($customFields): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="order-information">

                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Order Reference') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutOrderReference()); ?>
                    </div>
                </div>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Delivery Date') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutDate()); ?>
                    </div>
                </div>
            </div>

            <div class="order-information">
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></strong>
                    <div class="box-content">
                        <?php echo nl2br($this->escapeHtml($customFields->getCheckoutComment())); ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
