<?php
/** @var Magepow\CheckoutCustom\Block\Order\CustomFields $block */

/** @var Magepow\CheckoutCustom\Model\Data\CustomFields $customFields */
$customFields = $block->getCustomFields($block->getOrder());
?>
<?php if($customFields): ?>
    <div class="block block-order-details-view">
        <div class="block-content">
            <div class="box">
                <div class="box-content">
                    <strong><?php /* @escapeNotVerified */ echo __('Order Reference') ?>:</strong>
                    <?php echo $this->escapeHtml($customFields->getCheckoutOrderReference()); ?><br>
                    <strong><?php /* @escapeNotVerified */ echo __('Delivery Date') ?>:</strong>
                    <?php echo $this->escapeHtml($customFields->getCheckoutDate()); ?>
                </div>
            </div>

            <div class="box">
                <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></strong>
                <div class="box-content">
                    <?php echo nl2br($this->escapeHtml($customFields->getCheckoutComment())); ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
